name: kornli
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch>=2.0.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - tqdm>=4.65.0
  - sentencepiece>=0.1.99
  - pip
  - pip:
    - transformers>=4.30.0
